name: 'Self-Hosted Renovate'
description: 'GitHub Action to run self-hosted Renovate.'
author: 'Jeroen de Bruijn'
branding:
  icon: refresh-cw
  color: blue
inputs:
  configurationFile:
    description: 'Configuration file to configure Renovate'
    required: false
    default: src/config.js
  token:
    description: |
      GitHub personal access token that Renovate should use. This should be
      configured using a Secret.
    required: true
runs:
  using: node12
  main: dist/index.js
