name: 'Renovate Bot GitHub Action'
description: 'GitHub Action to run self-hosted Renovate.'
author: 'Jeroen de Bruijn'
branding:
  icon: refresh-cw
  color: blue
inputs:
  configurationFile:
    description: |
      Configuration file to configure Renovate. Either use this input or the
      'RENOVATE_CONFIG_FILE' environment variable.
    required: false
  token:
    description: |
      GitHub personal access token that Renovate should use. This should be
      configured using a Secret. Either use this input or the 'RENOVATE_TOKEN'
      environment variable.
    required: false
  useSlim:
    description: |
      Use a lightweight renovate container without any third-party binaries.
      Defaults to true if not set.
    required: false
  env-regex:
    description: |
      Override the environment variables which will be passsed into the renovate container.
      Defaults to `^(?:RENOVATE_\\w+|LOG_LEVEL|GITHUB_COM_TOKEN|NODE_OPTIONS)$`
    required: false
runs:
  using: node16
  main: dist/index.js
