name: 'Self-Hosted Renovate'
description: 'GitHub Action to run self-hosted Renovate.'
author: 'Jeroen de Bruijn'
branding:
  icon: refresh-cw
  color: blue
inputs:
  configurationFile:
    description: |
      Configuration file to configure Renovate. Either use this input or the
      'RENOVATE_CONFIG_FILE' environment variable.
    required: false
  token:
    description: |
      GitHub personal access token that Renovate should use. This should be
      configured using a Secret. Either use this input or the 'RENOVATE_TOKEN'
      environment variable.
    required: false
runs:
  using: node16
  main: dist/index.js
