name: Renovate
on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.147.0
        with:
          configurationFile: solr/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
          useSlim: false
        env:
          RENOVATE_FORK_TOKEN: ${{ secrets.RENOVATE_FORK_TOKEN }}
          LOG_LEVEL: "debug"
          RENOVATE_DOCKER_USER: "1000:0"
          RENOVATE_BINARY_SOURCE: "global"
